server.port: ${PORT:8090}
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: nareknaltakyan1@gmail.com
    password: pjbilbiuomzgnnow
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DB:diploma_auth}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:Ln#94954838}
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 580000
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: true
  flyway:
    baseline-on-migrate: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss